### ISSUE TITLE
Get the current compiler and path/filename from the callback of a custom filter

### ISSUE THREAD

**Issue by rik43** [pug-php/pug#101]
in custom filter we need to get template path. 
for example, i make include-markdown filter and can support insert by relative paths. 
or insert images by relative paths. 
Compiler class contain $filename property, but protected. 

example in custom filter usage:
```php
public function __invoke(Filter $node, Compiler $compiler)
{
    $templateFilename = $compiler->getFilename();
}
```

**Comment by kylekatarnls** [comment]
No problem,

It seems relevant. Will do it soon.

**Comment by kylekatarnls** [comment]
You can now upgrade to 2.5.2 and use `$compiler->getFilename()`.

Thanks,

**Comment by rik43** [comment]
awesome! Thanks!

**Comment by kylekatarnls** [comment]
I re-open to consider how to make this feature compatible with **pug-php** version 3.

**Comment by rik43** [comment]
first, check if someone is using it.
I, do not use this library now.

**Comment by kylekatarnls** [comment]
Fixed by https://github.com/phug-php/compiler/releases/tag/0.5.15:

This is the new way to get the filename:
```php
public function __invoke($source, $options, Compiler $compiler)
{
    $templateFilename = $compiler->getPath();
}
```
