### ISSUE TITLE
Error concerning mixins in JS expressionLanguage mode

### ISSUE THREAD

**Issue by dadajuice** [pug-php/pug#103]
Hi,

I have a question concerning how to use mixin when using expressionLanguage js option. I've tried the basic mixin example provided on the Pug website : 

```pug
mixin list
  ul
    li foo
    li bar
    li baz

doctype html
html
  head
    title Example
  body
    h1 Testing mixins
    +list
 ```

I'm constructing the Pug instance with the following code : 
```php
$options = [
    'basedir' => ROOT_DIR . '/public',
    'expressionLanguage' => 'js',
    'upToDateCheck' => true
];
$pug = new Pug($options);
echo $pug->render("test.pug");
```

Which results in an error : 
```
Error on the mixin "list" in test.pug line 13: Unexpected ? in on line 1 near from $attributes)) ?
```

But, if I use `'expressionLanguage' => 'auto'` instead of `js` it works as expected. Maybe I'm declaring or using the mixin incorrectly in js mode, so I was wondering how I could make it work.

Thanks a lot !

**Comment by kylekatarnls** [comment]
Hi,

This is a bug. I will fix it.

**Comment by kylekatarnls** [comment]
Hi, please update to the last version, it should be fixed.

**Comment by dadajuice** [comment]
Oh wow ! I updated to version 2.5.3 and it works. Thanks a lot for everything! I'm closing the issue.
