### ISSUE TITLE
js equivalent of isset()

### ISSUE THREAD

**Issue by webdevian** [pug-php/pug#107]
Using `'expressionLanguage' => 'js'`, I have the following code:

```pug
if url
  // Do something with url
else
  // Do something else
```
It compiles to 
```php
if($url)
```
If url is not defined in the locals I get a php warning `Undefined variable: url`.

I would expect this if statement to evaluate the undefined `url` variable as falsey, and not throw a warning

Or is there a different way I can write the if statement so that is compiles to something like `if(isset($url) || $url)`?

**Comment by kylekatarnls** [comment]
Hi,

PHP functions are allowed in JS mode:
```pug
if isset(url) && url
  p ok
else
  p ko
```

In PHP mode, just add the `$`:
```pug
if isset($url) && $url
  p ok
else
  p ko
```

Next version will follow the tale-jade way and append `isset`automatically.

**Comment by kylekatarnls** [comment]
isset is no longer necessary in pug-php 3 thanks to the check feature: https://phug.selfbuild.fr/#uncheck-check-code
Hope you will enjoy this new version.
