### ISSUE TITLE
Automatically change the created object after the loop?

### ISSUE THREAD

**Issue by dzpt** [pug-php/pug#108]
Today i notice that the parsing engine automatically changes the created object after the loop.
Example:
i have the topic object with phone property
`div=$topic->phone`

behind it i have the `$topics` list which contains many other `$topic` objects and show each of item like this:
```
each topic in topics
 // anything in the block
```

Then the `$topic->phone` at the beginning will be change to the `$topic->phone` (the item of `$topics`)
I can't use the `$topic` after the loop

I can't use the same object name in the page?!

**Comment by kylekatarnls** [comment]
Indeed each is not scoped, it means you get the PHP native behaviour, like when you do:

```php
$topic = 1;

foreach (array(2) as $topic) {
}

// now $topic = 2
```
