### ISSUE TITLE
Parent/root Tag needed?

### ISSUE THREAD

**Issue by marcus-at-localhost** [pug-php/pug#118]
Hey,
I use Pug to generate HTML fractions without wrapping `<html>` or so.

To me it seems like I always need a wrapping parent tag on top.

Situation:
```pug
div.x
  p 1
div.y
  p 2
```
results in

```html
<div class="x">
  <p>1</p>
</div>
```

and
```pug
div
  div.x
    p 1
  div.y
    p 2
```
results correctly in this:
```html
<div>
  <div class="x">
    <p>1</p>
  </div>
  <div class="y">
    <p>2</p>
  </div>
</div>
```

do I miss something?

**Comment by marcus-at-localhost** [comment]
I close this for now, since it seems to be an issue somewhere else in my chain...

**Comment by marcus-at-localhost** [comment]
Here is what's happened.

this:
```pug
div.x
  p 1
div.y
  p 2
```
is correctly rendered as:

```html
<div class="x"><p>1</p></div><div class="y"><p>2</p></div>
```
then, this fragment is parsed by https://github.com/erusev/parsedown-extra

and parsedown-extra drops every html after the first block, if it's in one line, and just outputs:

```html
<div class="x"><p>1</p></div>
```
See also: https://github.com/erusev/parsedown-extra/issues/90#issue-142629807

My solution is to turn on `prettyprint => true` in Pug and then it works.

Rare use case, but well

**Comment by kylekatarnls** [comment]
Hi, thanks for feedback. I do not understand the point of passing HTML to parsedown-extra.

If what you want is using parsedown inside your pug templates, you should consider using pug filters:

```php
$pug->filter('parsedown', function($node, $compiler){
    foreach ($node->block->nodes as $line) {
        $output[] = $compiler->interpolate($line->value);
    }
    $extra = new ParsedownExtra();

    return $extra->text(implode("\n", $output));
});
```

It allow you to do:
```pug
div.x
  p
    :parsedown
      # Header {.sth}
```
