### ISSUE TITLE
Nest mixin attributes confused

### ISSUE THREAD

**Issue by Riant** [pug-php/pug#126]
Hello,

I encountered an issue with the following code:
```pug
// mixin
mixin link($text)
  a(href='#')&attributes(attributes)= $text
mixin wrap_link($text)
  span&attributes(attributes)
    +link($text)

// html
+wrap_link('Hello').span
```

I expected to get:
```html
<span class="span"><a href="#">Hello</a></span>
```

But I actually get:
```html
<span class="span "><a href="#" class="span ">Hello</a></span>
```

Thanks!

**Comment by kylekatarnls** [comment]
Indeed, it's a mistake, the `$attributes` variables seems to be kept. We will fix that in the next major version (https://github.com/phug-php). Meanwhile here is a trick to fix the problem:

```pug
// mixin
mixin link($text)
  a(href='#')&attributes(attributes)= $text
mixin wrap_link($text)
  span&attributes(attributes)
    - unset($attributes)
    +link($text)

// html
+wrap_link('Hello').span
```

**Comment by kylekatarnls** [comment]
You can update to 3.0.0-alpha2, it should be fixed. Please don't hesitate to test the new pug-php 3 and give us your feedback.
