### ISSUE TITLE
Conditional with two variable

### ISSUE THREAD

**Issue by NekoOs** [pug-php/pug#127]
Content into index.php
```php
$pug = new Pug(array(
    'extension' => '.pug'
));
$pug->render('vista.pug', [
    'variable1' => 150,
    'variable2' => 150
]);
```
Content into vista.pug
```jade
if (variable1 == variable2)
      a exito
 else
      a fracaso
response: Notice: Use of undefined constant dos - assumed 'dos'
```
# Error case
```jade
if (variable1 == "#{variable2}")
      a exito
 else
      a fracaso
response: fracaso
```

```jade
if (variable1 == !{variable2})
      a exito
 else
      a fracaso
response: fracaso
```

# Succefull case
```jade
if (variable1 == "150")
      a exito
 else
      a fracaso
response: exito
```

```jade
if ($variable1 == $variable2)
      a exito
 else
      a fracaso
response: exito
```

How can I make a comparison of variables without using php variables.

`PD: Sorry the semantics but I do not speak English`

**Comment by kylekatarnls** [comment]
Hi, your first code can work with js option: "expressionLanguage" => "js" added on the Pug constructor array. The codes on your paragraph Error cases are not supposed to work neither in the last version of Pugjs nor in pug-php. Else parentheses are not necessary and if statements can contain PHP code.

**Comment by Cantuares** [comment]
Thanks @kylekatarnls!
