### ISSUE TITLE
pug file compiles fine with pug-cli, but fails with pug-php

### ISSUE THREAD

**Issue by iAlex97** [pug-php/pug#128]
My index.pug compiles just fine to html when using pug-cli, but gives 

`Uncaught ErrorException: /var/www/html/sheba_new/jade/dump/_index_dump.pug (2) : /var/www/html/sheba_new/jade/dump/_index_dump.pug (2) : Unexpected token "indent"`

when trying to compile it 'render' it with pug-php.

Also, why is that I'm declaring an extension attribute in the Pug builder, but when I;m rendering the file I have to specify its full filename?

ex:
`echo $pug->render("jade/pages/index");` will render a blank page
`echo $pug->render("jade/pages/index.pug");` renders the needed file

**Comment by kylekatarnls** [comment]
Extension option is for include and extend only. For your indent error, we need the pug content. Thanks.

**Comment by iAlex97** [comment]
Thanks for clarifying the extension part. As for the error, the file that is causing this is just an array:

```
-
	var index = {
		"sec_1":{
			"el_1": "item1",
			"el_2": "item2",
			"el_3": "item3",
			"el_4": "item4",
			"el_5": "item5"
		},
		"sec_2":{
                ...
```

but I've managed to get away by doing so:

```
-
-	var index = {
-		"sec_1":{
-			"el_1": "item1",
-			"el_2": "item2",
-			"el_3": "item3",
-			"el_4": "item4",
-			"el_5": "item5"
-		},
-		"sec_2":{
```

After that it's complaining about missing the closing bracket (`index = {\nMissing closing: }`)

How should I declare these arrays? And sorry for asking such questions, but I'm just getting started using Pug.

**Comment by kylekatarnls** [comment]
Until the next major version you will need a dash in front of each Line of raw code. The syntax you tried Will be available on 3.0. In pug-php, raw code is PHP. That allows you to put any native PHP class declaration, array/object. So you should use the array() syntax. If you realy want to use JS style, set the expressionLanguage to js, it will translater JS info PHP code but you will no longer be able to use PHP in your templates.

**Comment by iAlex97** [comment]
Thanks for the tip, but it's still complaining about can you please provide a little example?

I've tried with `array()` and `[]` which both work in my PHP environment.

```
$index = array (	
		"sec_1"=>array(
			"el_1"=> "item1",
			"el_2"=> "item2",
			"el_3"=> "item3",
			"el_4"=> "item4",
			"el_5"=> "item5"
		),
		"sec_2"=>array(...)
	);
```

and

```
$index = [	
		"sec_1"=>array[
			"el_1"=> "item1",
			"el_2"=> "item2",
			"el_3"=> "item3",
			"el_4"=> "item4",
			"el_5"=> "item5"
		],
		"sec_2"=>array[...]
	];
```

Both will lead me to an `_index_dump.pug (3) : Unexpected token "indent"` exception.

**Comment by kylekatarnls** [comment]
You need a dash in front of each line or you can use the :php filter.

**Comment by iAlex97** [comment]
I have added a dash before each line and still can't get it to work... This is driving me nuts!
It always ends up complaining about missing the ending accolade (`index = {\nMissing closing: }`)

I've checked 10 times with Sublime and they're closed correctly, maybe there's an indentation problem? How should I do these multi-dimensional arrays without any filters?

**Comment by kylekatarnls** [comment]
What syntax did you choose? And did you set expressionLanguage to js? And so please give your new code with the parent, previous and next tag included if exist. PS array[] is wrong, it's array() or []

**Comment by iAlex97** [comment]
I haven't set the expressionLanguage to js as I'd like to be able to use PHP stuff inside.

They're included in the `index.pug` file inside a `block bage` like this:

```
block title
	title Home

block page
	// Page Header
	include ../_header-variant-1
	include ../dump/_index_dump
	include ../dump/_category_dump

	// Page Content
	include _index-page-content

	// Page Footer
	include ../_footer-variant-1
	// FOOTER LINK
```

About the array thing, you're absolutely right, but that was just a typo when I wrote the comment here unfortunately.

**Comment by kylekatarnls** [comment]
So you should not have accolade in your code. It's inconsistent with the error you mention, please the current code (not the layout) with tags, dashes and indent and the actual error.

**Comment by iAlex97** [comment]
I don't know what you mean by 'current code'.

__fixed_dump.pug_
```
- var header = {
-	"sec_1": {
-	"el_1": "Orders",
-	"el_2": "Compare",
-	"el_3": "Wishlist",
-	"el_4": "My Account",
-	"el_5": "muies",
-	"el_6": "USD",
-	"el_7": "EUR"
-	},
-	"sec_2": {
-	"el_1": "home",
-	"el_2": "pages",
-	"el_3": "Typography",
-	"el_4": "404",
-	"el_5": "Blog style",
-	"el_6": "Blog Masonry 2 cols",
-	"el_7": "Blog Masonry 3 cols",
-	"el_8": "Blog Grid 2 cols",
-	"el_9": "Blog Grid 3 cols",
-	"el_10": "Blog Boxed",
-	"el_11": "Post formats",
-	"el_12": "Image Format",
-	"el_13": "Gallery Format",
-	"el_14": "Audio Format",
-	"el_15": "Video Format",
-	"el_16": "Quote Format",
-	"el_17": "Link Format",
-	"el_18": "Aside Format",
-	"el_19": "Header style",
-	"el_20": "Header style 1",
-	"el_21": "Header style 2",
-	"el_22": "Header style 3",
-	"el_23": "Footer style",
-	"el_24": "Footer style 1",
-	"el_25": "Footer style 2",
-	"el_26": "Footer style 3",
-	"el_27": "Sidebar style",
-	"el_28": "Sidebar left",
-	"el_29": "Sidebar right",
-	"el_30": "No sidebar",
-	"el_31": "Products",
-	"el_32": "About",
-	"el_33": "Blog",
-	"el_34": "Contacts",
-	"el_35": "My Cart",
-	"el_36": "Agrafe earrings",
-	"el_37": "4 x ",
-	"el_38": "$258.89",
-	"el_39": "Subtotal: ",
-	"el_40": "$1,035.56"
-	}
-}
```

This var is inside a pug file that is included like this:
__skeleton.pug_
```
include _mixins

include dump/_fixed_dump

block variables
```

and my _index.pug_ extends the skeleton like so:
`extends  ../_skeleton`

From PHP I'm trying to serve it like so:
```
<?php
	namespace Pug;

	require __DIR__ . '/vendor/autoload.php';

	$pug = new Pug(array(
	'prettyprint' => true,
	 'extension' => '.pug',
	 /*'cache' => 'pathto/writable/cachefolder/'*/
	));

	echo $pug->render("jade/pages/index.pug");
?>
```

I bought this template online and I'm trying to figure out how it works. I'm sorry for all the hassle!

**Comment by kylekatarnls** [comment]
Declare header with PHP array syntax.

**Comment by iAlex97** [comment]
I've managed to get away past that error using your suggestion and my array looks like this now:

```
$header = array(
	"sec_1"=> array(
	"el_1"=> "Orders",
	"el_2"=> "Compare",
	"el_3"=> "Wishlist",
	"el_4"=> "My Account",
	"el_5"=> "muies",
	"el_6"=> "USD",
	"el_7"=> "EUR"
	),
	"sec_2"=> array(
	"el_1"=> "home",
	"el_2"=> "pages",
	"el_3"=> "Typography",
	"el_4"=> "404",
	"el_5"=> "Blog style",
	"el_6"=> "Blog Masonry 2 cols",
	"el_7"=> "Blog Masonry 3 cols",
	"el_8"=> "Blog Grid 2 cols",
	"el_9"=> "Blog Grid 3 cols",
	"el_10"=> "Blog Boxed",
	"el_11"=> "Post formats",
	"el_12"=> "Image Format",
	"el_13"=> "Gallery Format",
	"el_14"=> "Audio Format",
	"el_15"=> "Video Format",
	"el_16"=> "Quote Format",
	"el_17"=> "Link Format",
	"el_18"=> "Aside Format",
	"el_19"=> "Header style",
	"el_20"=> "Header style 1",
	"el_21"=> "Header style 2",
	"el_22"=> "Header style 3",
	"el_23"=> "Footer style",
	"el_24"=> "Footer style 1",
	"el_25"=> "Footer style 2",
	"el_26"=> "Footer style 3",
	"el_27"=> "Sidebar style",
	"el_28"=> "Sidebar left",
	"el_29"=> "Sidebar right",
	"el_30"=> "No sidebar",
	"el_31"=> "Products",
	"el_32"=> "About",
	"el_33"=> "Blog",
	"el_34"=> "Contacts",
	"el_35"=> "My Cart",
	"el_36"=> "Agrafe earrings",
	"el_37"=> "4 x ",
	"el_38"=> "$258.89",
	"el_39"=> "Subtotal: ",
	"el_40"=> "$1,035.56"
	)
)
$footer = array(
	"el_1"=> "Our products are a combination of classic and modern style; we can satisfy any demands of customers, that is why we have so many fans. You will <br class='veil reveal-lg-block'> always be popular with our jewelry; the magical shine of our products will bring you the best of luck!",
	"el_2"=> "<span class='text-bold'>Turquoise</span> 2016 | <a href='privacy.html'>Privacy Policy</a>"
)
$footer_variant_3 = array(
	"sec_1"=>array(
	"el_1"=> "Categories",
	"el_2"=> "Earrings",
	"el_3"=> "Necklaces",
	"el_4"=> "Brooches",
	"el_5"=> "Rings",
	"el_6"=> "",
	"el_7"=> "",
	"el_8"=> ""
	),
	"sec_2"=>array(
	"el_1"=> "Posted by <a class='text-normal' href='blog-list.html'>Alis</a>",
	"el_2"=> "Softer Than Chain",
	"el_3"=> "Posted by <a class='text-normal' href='blog-list.html'>Alis</a>",
	"el_4"=> "The 'It' Jewellers Flying The Flag For Fairtrade",
	"el_5"=> "Posted by <a class='text-normal' href='blog-list.html'>Alis</a>",
	"el_6"=> "The Rock Hound Fairtrade Earrings Review",
	"el_7"=> "Posted by <a class='text-normal' href='blog-list.html'>Alis</a>",
	"el_8"=> "Paris Jewellery Hot Off The Streets",
	"el_9"=> "Posted by <a class='text-normal' href='blog-list.html'>Alis</a>",
	"el_10"=> "Image Format"
	),
	"sec_3"=>array(
	"el_1"=> "<a class='text-normal' href='blog-list.html'>Alis</a> on",
	"el_2"=> "Marvelous …All the emerald jewelry...",
	"el_3"=> "<a class='text-normal' href='blog-list.html'>Alis</a> on",
	"el_4"=> "Nice tips, it will really help to people...",
	"el_5"=> "<a class='text-normal' href='blog-list.html'>Alis</a> on",
	"el_6"=> "I would love to own an emerald like...",
	"el_7"=> "",
	"el_8"=> "",
	"el_9"=> "",
	"el_10"=> ""
	)
)
$sidebar = array(
	"el_1"=> "Search",
	"el_2"=> "Categories",
	"el_3"=> "Earrings",
	"el_4"=> "Necklaces",
	"el_5"=> "Brooches",
	"el_6"=> "Rings",
	"el_7"=> "Recent Posts",
	"el_7_1"=> "Posted by <a href='blog-list.html'>Shane Doe</a>",
	"el_8"=> "Softer Than Chain",
	"el_8_1"=> "Posted by <a href='blog-list.html'>Shane Doe</a>",
	"el_9"=> "The &#39;It&#39; Jewellers Flying The Flag For Fairtrade",
	"el_9_1"=> "Posted by <a href='blog-list.html'>Shane Doe</a>",
	"el_10"=> "Paris Jewellery Hot Off The Streets",
	"el_10_1"=> "Posted by <a href='blog-list.html'>Shane Doe</a>",
	"el_10_2"=> "New! New! NEW !!!",
	"el_11"=> "Recent Reviews",
	"el_12"=> "by ",
	"el_13"=> "Shane Doe",
	"el_14"=> "Amulette de Cartier long necklace ",
	"el_15"=> "by ",
	"el_16"=> "Shane Doe",
	"el_17"=> "Floral Vine Teardrop Natural Shell .925 Silver Earrings",
	"el_18"=> "by ",
	"el_19"=> "Shane Doe",
	"el_20"=> "6-mm Round Birthstone Stud Earrings",
	"el_21"=> "Product Tags",
	"el_22"=> "Earrings",
	"el_23"=> "Necklaces",
	"el_24"=> "Brooches",
	"el_25"=> "Rings",
	"el_26"=> "Recent Comments",
	"el_27"=> "Shane Doe",
	"el_28"=> " on",
	"el_29"=> "Marvelous …All the emerald jewelry...",
	"el_30"=> "Shane Doe",
	"el_31"=> " on",
	"el_32"=> "Nice tips, it will really help to people...",
	"el_33"=> "Shane Doe",
	"el_34"=> " on",
	"el_35"=> "I would love to own an emerald like...",
	"el_36"=> "About <br class='veil reveal-lg-block'> Our Store",
	"el_37"=> "We are offering you the unique goods because our product is the real treasure.",
	"el_38"=> " If you are a true fan, you&#39;ll love it. We have a tremendous variety in comparison to all of our competitors. Our collection is like a sea pearl among simple stones. Our devoted clients have noticed that our goods are the index of true, elegant taste. ",
	"el_38_1"=> "",
	"el_39"=> "Archives",
	"el_40"=> "March 2016",
	"el_41"=> "February 2016",
	"el_42"=> "January 2016",
	"el_43"=> "Follow us",
	"el_44"=> "Read our latest news on any of these social networks!",
	"el_45"=> "Get latest news delivered daily!",
	"el_46"=> "We will send you breaking news right to your inbox",
	"el_47"=> "Twitter Widget",
	"el_48"=> "Facebook",
	"el_49"=> "Calendar"
)
```

but I'm getting another wired error now `PHP Parse error:  syntax error, unexpected '?>', expecting ')' in pug.stream://data;`

It's a long apache2 error, but from what I see it really inserts an '?>' after my array declaration:
`<?php $header=array( ?> \n  "sec_1"=> array(\n  "el_1"=> "Orders"`

same happens when using [ ] array declaration.

**Comment by kylekatarnls** [comment]
Don't forget **;** as in normal PHP after each declaration and dashes in each line. Else you can start the first line with :php then put your PHP code indented once more (with no dashes).

**Comment by iAlex97** [comment]
I did put the **;** and got the same result. Do I have to use the php filter? If so, how can I do this?

**Comment by kylekatarnls** [comment]
PHP filtres examples:
Input: https://github.com/pug-php/pug/blob/master/tests/templates/filter.php.jade
Result: https://github.com/pug-php/pug/blob/master/tests/templates/filter.php.html

Input: https://github.com/pug-php/pug/blob/master/tests/templates/getter.jade
Result: https://github.com/pug-php/pug/blob/master/tests/templates/getter.html


Raw code examples:
Input: https://github.com/pug-php/pug/blob/master/tests/templates/deep-objects.jade
Result: https://github.com/pug-php/pug/blob/master/tests/templates/deep-objects.html

**Comment by kylekatarnls** [comment]
Hope now all is clear with the PHP embedded syntax. If not feel free to ask.
