### ISSUE TITLE
localisation of strings

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#131]
I need to run all strings in plain language in a php localisation function.

e.g. `__( 'some string', 'mytheme' )` or `_e( 'some string', 'mytheme' )` (shortcuts to php gettext)

What is the best way to achieve this?

I could build a data array and pre populate it with strings and pass it to pug:

```
$data = [
  'string1' => __( 'some string', 'mytheme' )
];
```
and than interpolate `string1` inside pug.

But surely there is a better way :)

**Comment by kylekatarnls** [comment]
First gettext can parse pug files (I use python language, maybe now there is a pug option right in the settings), so you can use right in templates:

```pug
p=_("Hello world")
```

I would recommend this approach because it makes templates easiest to work with and avoid passing a lot of data from the controller.

If you have some common and dynamic texts, use the share method:
```php
$pug->share(array(
  'language' => 'en',
  'title' => 'My website'
));
```

**Comment by sandrodz** [comment]
works great :) I use both methods yes.

btw, it needs textdomain otherwise it doesn't work in php. e.g. p=__("Hello world","domain")

Is it possible to add domain during compilation? just to have pug files cleaner.

**Comment by kylekatarnls** [comment]
Just add this on the top of the template or in a layout/include:
```pug
- textdomain("domain")
header
  p=_("Hello world")
  | Pug template content...
```

**Comment by sandrodz** [comment]
Thanks!

**Comment by sandrodz** [comment]
@kylekatarnls last question I promise ^_^ do you know any more elegant way of writing these?

`#{__()}` seems terrible.

**Comment by sandrodz** [comment]
<img width="543" alt="screen shot 2017-05-05 at 8 28 56 pm" src="https://cloud.githubusercontent.com/assets/8479569/25754808/a0060bee-31d1-11e7-9e5f-6fef11fdb20d.png">

**Comment by kylekatarnls** [comment]
Not realy better. You can do this:
```pug
| 120
=_(...)
=" "
=_(...)
```

**Comment by sandrodz** [comment]
@kylekatarnls 

I get this error: `Undefined variable: textdomain on line 1, offset 1`

<img width="1234" alt="screen shot 2018-01-01 at 8 44 07 pm" src="https://user-images.githubusercontent.com/8479569/34470562-7fa0594c-ef34-11e7-9bcd-e72b71ffe272.png">

**Comment by kylekatarnls** [comment]
Hi, I suspect gettext to not be installed and enabled, can you check it with `phpinfo()`?

**Comment by sandrodz** [comment]
I have the module:

![screen shot 2018-01-01 at 8 56 23 pm](https://user-images.githubusercontent.com/8479569/34470634-2d4b017c-ef36-11e7-966c-ac3f70dc1213.png)

**Comment by sandrodz** [comment]
I'm using: `'expressionLanguage' => 'js'`

**Comment by kylekatarnls** [comment]
Authors are just credits of installed modules. They can be installed without being enabled.

The needed setting is:

![phpinfo-gettext](https://user-images.githubusercontent.com/5966783/34479642-4645b7e0-efa8-11e7-962d-6a0700482de7.png)

Also be sure, this is the same PHP program (run `- phpinfo()` directly from the pug template to be sure), you can have Apache and CLI with different settings, and potentially different versions of PHP installed.

**Comment by sandrodz** [comment]
Yes you were right. Updated my docker containers with gettext module: https://github.com/wearede/DevCeption/commit/6f72470ca022c4cb3dc8e540842a350555f7c6f4

**Comment by kylekatarnls** [comment]
Great!

**Comment by sandrodz** [comment]
Hi, I'm still having issues with this.

It only works if I add text domain inside the `__` calls e.g.

<img width="606" alt="screen shot 2018-01-12 at 9 25 08 pm" src="https://user-images.githubusercontent.com/8479569/34887205-1ff24be6-f7df-11e7-9903-7bffcd3eba7c.png">

Without text domain strings are not translated.

I have:

`- textdomain(txtdomain)¬` at the beginning of the base pug file.

**Comment by kylekatarnls** [comment]
Hi,

The gettext function take exactly 1 argument, no more. And this come with `- textdomain()` function separated.

Can I see your `__()` function definition because I cannot understand how it can be gettext and support 2 arguments.

**Comment by sandrodz** [comment]
It is a get text wrapper for WordPress: https://codex.wordpress.org/I18n_for_WordPress_Developers

Sorry for confusion!

**Comment by kylekatarnls** [comment]
I think it's a "feature" of this plugin, see the documentation (and also the file source https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/l10n.php#L121):

```
(string) (optional) Domain to retrieve the translated text
Default: 'default'
```
What I understand is: if you don't specify, the domain as second argument, it will be replaced by the string `"default"`. So `textdomain(txtdomain)` is never taken into account. That's seems a bit dummy to me according to gettext standard usage but it can be some easier for small app  with only one text domain, so you just have to name this domain "default".

You could do your own wrapper-wrapper:
```php
function ___($text, $domain = null) {
  return __($text, $domain === null ? textdomain() : $domain);
}
function __e($text, $domain = null) {
  return _e($text, $domain === null ? textdomain() : $domain);
}
```
