### ISSUE TITLE
Dynamic mixins?

### ISSUE THREAD

**Issue by Spone** [pug-php/pug#138]
I tried to use interpolation in mixin name, as allowed in Pug (see this issue https://github.com/pugjs/pug/issues/1282) but it does not seem to work with pug-php.

I encountered an issue with the following code:
```pug
mixin hit-article(data)
  = "hit-article works!"

mixin hit(type)
  .hit
    +#{'hit-' + type}

+hit('article')
```

I expected to get:
```html
<div class="hit">hit-article works!</div>
```

But I actually get:
```html
<div class="hit">+hit-article</div>
```

Will you support this feature?

**Comment by kylekatarnls** [comment]
Thanks, I plan it for version 3.0. Depending on my free time, maybe I could add it before. If you can, feel free to propose a pull-request.

**Comment by kylekatarnls** [comment]
Implemented, please upgrade to 2.6.0.

**Comment by Spone** [comment]
That was fast, thanks!

**Comment by Spone** [comment]
I updated to 2.6.0, but I have this error when I try to use dynamic mixins:

`Notice: Undefined index: hit-article_mixin in pug.stream:// [...]`
`Fatal error: Uncaught Error: Function name must be a string in pug.stream:// [...]`

**Comment by kylekatarnls** [comment]
You should have the option `allowMixinOverride` set to `true`. If so, you cannot have dash `-` in your mixin names for now.

**Comment by kylekatarnls** [comment]
`Undefined index: hit-article_mixin` is not about dynamic mixins use. It means the declaration for the mixin is missing. Please show the `mixin hit-article` declaration and the call.

**Comment by Spone** [comment]
I did not change the default value for this option. I have other mixins with dashes `-` in the name and they work correctly.

**Comment by kylekatarnls** [comment]
Yes sorry, it was a bad interpretation, I removed my message. The dynamic mixin try to access **hit-article**, that seems right. Does the declaration exists?

**Comment by kylekatarnls** [comment]
As you can see, this unit test succeed: https://github.com/pug-php/pug/blob/master/tests/templates/mixins.dynamic.jade
Can you provide a unit test to reproduce your bug?

**Comment by Spone** [comment]
The simple test case works for me. There is probably an issue somewhere else in my code.

I fixed my issue by enabling the `'pugjs' => true` option.
