### ISSUE TITLE
pugjs + cache: upToDateCheck not supported?

### ISSUE THREAD

**Issue by Spone** [pug-php/pug#141]
Hello,

I switched to using `pugjs` mode for rendering, but I'd like to keep using the cache feature.
Right now, even with the `upToDateCheck` set to `true`, the js files in my cache folder are refreshed every time I reload the page.

Here is the config I use:
```php
$pug = new \Pug\Pug([
    'pugjs' => true,
    'cache' => get_template_directory() . '/cache/pug',
    'upToDateCheck' => false,
]);
```

Is this the expected behavior?

**Comment by kylekatarnls** [comment]
This unit test: https://github.com/pug-php/pug/blob/master/tests/features/pugjs.php#L47
is supposed to check that the cached file is not recreated if the last modified timestamp of the file is newer that the source file. Are `filemtime('yourpugfile.pug')` and `filemtime('yourcachefile.js')` accurate?

**Comment by Spone** [comment]
They seem to be, when I check them in the PHP interactive shell:

    $ php -a
    Interactive mode enabled

    php > echo filemtime('cache/pug/icon.js') . ' / ' . filemtime('modules/icon/icon.pug');
    1496404382 / 1496404357

**Comment by kylekatarnls** [comment]
And if you reload the page `icon.pug` is still 357 and `icon.js` changed?

**Comment by Spone** [comment]
After reloading the page I get:

    php > echo filemtime('cache/pug/icon.js') . ' / ' . filemtime('modules/icon/icon.pug');
    1496404834 / 1496404357

**Comment by Spone** [comment]
I don't see the option `upToDateCheck` being used in [PugJsEngine.php](https://github.com/pug-php/pug/blob/master/src/Jade/Engine/PugJsEngine.php), maybe that's the reason?

**Comment by kylekatarnls** [comment]
`upToDateCheck` is not the point, the behavior of this option is:

`false`: never refresh at all (assume you cached all the templates on deploy)
`true`: refresh only if cacheTime < sourceTime

This check is done here when you use pugjs engine:
https://github.com/pug-php/pug/blob/master/src/Jade/Engine/PugJsEngine.php#L146

**Comment by Spone** [comment]
So there are actually two different issues:

- when I use `pugjs` AND set `'upToDateCheck' => false`, the cache is still refreshed but it shouldn't be
- when I use `pugjs` without the `upToDateCheck` option (or with `'upToDateCheck' => true`), the cache is refreshed even if the source file did not change

**Comment by kylekatarnls** [comment]
Hi, I reproduce the bug and will work on it.

**Comment by kylekatarnls** [comment]
It seems, pug-cli just touch the cached file but does not edit it. If you try the following:
```php
use Pug\Pug;

require 'vendor/autoload.php';

$pug = new Pug([
  'cache' => 'cache',
  'pugjs' => true,
]);

echo $pug->render('view.pug')."\n";
```
view.pug contains `p Hello`

You will obtain `<p>Hello</p>`

Then if you replace "Hello" with "Bye" in `cache/view.js` and re-run the php file, you will obtain `<p>Bye</p>`, then disable the cache option and re-run again, you get `<p>Hello</p>`, it's a proof the cache works, but the last modified time on `cache/view.js` is not accurate because pug-cli change this timestamp when it run the file.

So the lonely that could be needed would to restore the original timestamp after render.

**Comment by kylekatarnls** [comment]
Hi, please update to **2.6.3**, it allow upToDateCheck to work with pugjs and provide reliable modified timestamp for cached files. If you get troubles please re-open this issue.
