### ISSUE TITLE
How to use closure if render engine is pugjs

### ISSUE THREAD

**Issue by thiennq** [pug-php/pug#142]
Hi,

I'm using pugjs engine and I can't using closure in .pug file.
Did I do something wrong?

Here's my code:

View.php
```php
class View {
  public function __construct($obj) {
    $viewConfig = array(
      'pugjs' => true,
      'expressionLanguage' => 'js'
    );
    $pug = new Pug($viewConfig);
    $this->pug = $pug;
  }

  public function render($response, $file, $data = array()) {
    try {
      $double = function ($str) { return $str . $str; };
      $closures = [
         'double' => $double
      ]
      
      $filepath = $this->path . $file;
      $html = $this->pug->render($filepath, $data, $closures);
      $body = $response->getBody();
      $body->write($html);
    } catch (Exception $e) {
      ....
    }
 }
 ....
```

index.pug:
```pug
h1=double("abc")
```

Thank you!

**Comment by kylekatarnls** [comment]
`->render` has only 1 array argument. In your code only `$data` is available in the templates, `$closures` is ignored. Use this:

```php
$html = $this->pug->render($filepath, array_merge($data, $closures));
```

**Comment by thiennq** [comment]
@kylekatarnls Thank you, but I mentioned this:
[https://github.com/pug-php/pug#php-helpers-functions](https://github.com/pug-php/pug#php-helpers-functions)

to use PHP function in .pug file, not attach some variable, for example

```pug
p=money(12345)
```
will render
```html
<p>$12,345.00</p>
```

**Comment by thiennq** [comment]
@kylekatarnls Thank you, I'll try it.

**Comment by kylekatarnls** [comment]
Oh, and I'm sorry but functions cannot be passed throught pugjs engine. The pugjs option will convert all data as a JSON string and pass it to pug-cli. JSON can contain only strings, numbers, booleans, null, array, standard objects.

**Comment by thiennq** [comment]
@kylekatarnls: Thank for the great explanation 👍 

I tried to change config:
```php
    $viewConfig = array(
      'expressionLanguage' => 'js'
    );
```
use php engine but expressionLanguage is `js` and it works perfectly for me.
The syntax likes original `pugjs` but support php function (global function).

**Comment by thiennq** [comment]
Here the full solution:

**view.php**
```php
require_once('pug-helper.php');

class View {
  public function __construct($obj) {
    $viewConfig = array(
      'expressionLanguage' => 'js'
    );
    $pug = new Pug($viewConfig);
    $this->pug = $pug;
  }

  public function render($response, $file, $data = array()) {
    try {
      $filepath = $this->path . $file;
      $html = $this->pug->render($filepath, $data, $closures);
      $body = $response->getBody();
      $body->write($html);
    } catch (Exception $e) {
      ....
    }
 }
```

**pug-helper.php**
```php
function money($money) {
  return '$' . number_format($money);
};
```

**index.pug**
```pug
p=money(12345)
```

**The result:**
```html
<p>$12,345</p>
```
