### ISSUE TITLE
Slashes in locals are escaped by json_encode

### ISSUE THREAD

**Issue by tntrex** [pug-php/pug#147]
I'm using pug-php with nodejs pug-cli and found that slashes in locals had escaped by json_encode. It breaks all urls stored in locals.

For example, I have store favicon path in locals array:

```php
$LOCALS['site'] = [
	'colorScheme' => 'none',
	'favicon' => '/favicon.png'
];
```

And then i'm use it in my pug template:

```pug
link(rel="shortcut icon", href=site.favicon, type="image/png")
```

I'm getting broken favicon path on rendered page:

```html
<link rel="shortcut icon" href="\/favicon.png" type="image/png">
```

Is there way to pass some options to json_encode, like JSON_UNESCAPED_SLASHES etc.?

**Comment by kylekatarnls** [comment]
It probably should be the default. I create a unit test to reproduce the case.

**Comment by kylekatarnls** [comment]
Confirmed, soon fixed

**Comment by kylekatarnls** [comment]
Thanks for the help, please upgrade to 2.6.4 to get fixed escape.
