### ISSUE TITLE
Attribute with 'NULL' value is not rendering

### ISSUE THREAD

**Issue by glodov** [pug-php/pug#149]
I needed an attribute to be a "null" in HTML for some reason, so I tried:
`p(date='null')`
so it rendered just paragraph
so I am using 
`p(date='none')`
instead
But it seems as a bug

**Comment by kylekatarnls** [comment]
Bug confirmed and reproduced in the pug-demo: https://pug-demo.herokuapp.com/

However it works with Phug (the engine we are about to release that will replace the pug-php one for the version 3.0), to be short it means that will work on the next major release. So I prefer to first release the 3.0, then optionally make a patch for the 2.6.

**Comment by kylekatarnls** [comment]
You can update to `3.0.0-alpha2`, it should be fixed. Please don't hesitate to test the new pug-php 3 and give us your feedback.

**Comment by glodov** [comment]
thanks
