### ISSUE TITLE
Nested tag interpolation not supported

### ISSUE THREAD

**Issue by wolfgang42** [pug-php/pug#154]
Hello,

I encountered an issue with the following code:
```pug
p #[em #[strong Yow!]]
```

I expected to get:
```html
<p><em><strong>Yow!</strong></em></p>
```

But I actually get:
```html
<p><em>#[strong Yow!</em>]</p>
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi, thanks. This is now qualified to come with 2.7. And we will also work on it for our phug refactor (3.0).

**Comment by kylekatarnls** [comment]
You can now update to **2.7.0** to get nested interpolations working.

Thanks,
