### ISSUE TITLE
Interpolation at end of line in block tag strips trailing whitespace

### ISSUE THREAD

**Issue by wolfgang42** [pug-php/pug#156]
I encountered an issue with the following code:
```pug
blockquote.
	Well #[em hello]
	there, world!
```

I expected to get:
<blockquote>
  Well <em>hello</em>
  there, world!
</blockquote>

But I actually get:
<blockquote>Well <em>hello</em>there, world!</blockquote>

This appears to be the case for both tag and variable interpolation.

**Comment by kylekatarnls** [comment]
This is yet fixed in https://github.com/phug-php/phug so I will eventually fix it only after 3.0 release.

**Comment by kylekatarnls** [comment]
You can update to `3.0.0-alpha2`, it should be fixed. Please don't hesitate to test the new pug-php 3 and give us your feedback.
