### ISSUE TITLE
renderfile

### ISSUE THREAD

**Issue by anglerprasanna** [pug-php/pug#163]
I encountered an issue with the following code:
```
$pug->renderFile(__DIR__ . '/' . $path . '.pug', $vars);
Call to undefined method Pug\Pug::renderFile()
```

**Comment by kylekatarnls** [comment]
Hi,
`renderFile` is a method of version `3.0.0` wich is an alpha release (https://github.com/pug-php/pug/releases) I think you have the default minimum stability (stable) so you have `2.7.1`, `3.0.0` will be soon stable so I encourage you right now to install pug this way:

`composer require pug-php/pug "^3.0.0@alpha"`

**Comment by anglerprasanna** [comment]
@kylekatarnls thanks a lot!
