### ISSUE TITLE
Javascript Template Literal

### ISSUE THREAD

**Issue by keyurshah** [pug-php/pug#176]
Hello,

I encountered an issue with the following code:
```pug
- var fruit = 'grapes'
p= `${fruit}`
```

I expected to get:
```html
<p>grapes</p>
```

But I actually get:
```html
<p></p>
```

I'm trying to set a template literal per ES6

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

I am instantiating pug as follows

```
        $pug = new Pug([
            'expressionLanguage' => 'js',
        ]);
```

Thanks!

**Comment by kylekatarnls** [comment]
Hi, the ES6 literal is not supported (and most of ES6 syntaxes), except with the `'pugjs' => true,` but this option will totally disable PHP engine (class instances are flattened, PHP functions are not available) and will use the native node engine.

But, you can user simple concatenation:
```pug
- var fruit = 'grapes'
p= 'start' + fruit + 'end'
```

Or with `'expressionLanguage' => 'php'`, you can use PHP interpolation:
```phug
- $fruit = 'grapes'
p= "start ${fruit} end"
```

**Comment by keyurshah** [comment]
ok, thanks, i'll stick with the simle concatenation. appreciate the hard work on this great project!
