### ISSUE TITLE
Interested in sharing project using pug-php?

### ISSUE THREAD

**Issue by alessandro-fazzi** [pug-php/pug#182]
Hi maintainer(s) :)

I hope I'm using the right channel to communicate with you. I'll be really fast and concise: I maintain a WordPress plugin which enables developers to write their templates in PUG using your library. Are you interested in listing it somewhere? I've seen a list of 3rd party libs for PHP frameworks: could there be a list for CMSs too?

Me and my whole team are very thankful for the work you have done and are doing with pug-php and Phug. Kudos.

**Comment by kylekatarnls** [comment]
Great news! Fully agree with a CMS section. If you want, the documentation is open-source ([Edit] buttons in top right hand corner) else please give me a link to your plugin and I will add it soon.

**Comment by alessandro-fazzi** [comment]
Hello @kylekatarnls ,

thanks for your interest. I'd just add something like

```
## Pug in your favorite CMS

WordPress: https://github.com/welaika/wordless
```

just after the *Frameworks* list. Just to have 100% parity with other project mentioned.

Wordless does a lot of other things, but this is not the place where to do verbose sponsorship, imho.

What do you think about?

**Comment by kylekatarnls** [comment]
Hi, I will add it, my two cents: did you see you can embed assets with [pug-php/pug-assets](https://github.com/pug-php/pug-assets)? It does not include Sass, but less, stylus, coffee that might interest you. It would probably short-circuit assets wordpress management: to check.

**Comment by kylekatarnls** [comment]
https://phug-lang.com/#in-your-favorite-cms
