### ISSUE TITLE
unexpected text output false

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#185]
Hello,

I encountered an issue with the following code:
```pug
      div(class="ta-c mt-s mt-xl@l")
        a(href=o.hmore class="Btn Btn--ghost")=!__("More")+'&nbsp;'
          =o.t
```

I expected to get:
```html
More SomeText
```

But I actually get:
```html
falseSomeText
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello,
`!=` ouput as raw while `=!` output escaped then start an expression with `!`
https://www.phug-lang.com/#unescape-escape-code
