### ISSUE TITLE
undefined variable checking with if

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#186]
Hello,

![screen_shot_2018-01-10_at_10 39 49_am](https://user-images.githubusercontent.com/8479569/34761102-ce5868ae-f5fb-11e7-864b-45e3444ecb24.png)

I encountered an issue with the following code:
```pug
if an
```

I expected to get:
```html
nothing
```

But I actually get:
```html
undefined variable
```
Using `expressionLanguage => js`

Thanks!

**Comment by kylekatarnls** [comment]
Hi, please try to `composer update` it should fix your bug.

**Comment by sandrodz** [comment]
Works, thanks!
