### ISSUE TITLE
Boolean attributes

### ISSUE THREAD

**Issue by s4msung** [pug-php/pug#19]
With literal values this works as expected:

``` pug
input(type="checkbox", checked=true)
```

``` html
<input type="checkbox" checked>
```

Using variable assignment it renders boolean attributes wrong:

``` pug
input(type="checkbox", checked=isChecked)
```

``` html
<input type="checkbox" checked="true">
```

**Comment by kylekatarnls** [comment]
Confirmed. It's a regression, I add a test to keep this unbroken and will fix it as a priority.

**Comment by kylekatarnls** [comment]
Hi, it should be fixed, please update and retry.

**Comment by kylekatarnls** [comment]
I consider this issue as fixed, fell free to re-open it if you meet any problem.

**Comment by s4msung** [comment]
The next issue i run into because aria-haspopup is not a boolean attribute:

``` pug
a.dropdown-toggle(href="#", data-toggle="dropdown", role="button", aria-haspopup="true", aria-expanded="false")
```

rendered:

``` html
<a href="#" data-toggle="dropdown" role="button" aria-haspopup class="dropdown-toggle"></a>
```

expected:

``` html
<a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"></a>
```

Consider to maintain a list of boolean attributes like this https://github.com/kangax/html-minifier/issues/63 (can't find a complete list in w3c specs) to handle the correct rendering

**Comment by kylekatarnls** [comment]
Indeed, it's a big concern. I think, the most flexible way would be to differentiate `true` and `"true"` but the whitelist could be an easy quick fix. Thanks.

**Comment by kylekatarnls** [comment]
It should be fixed now if you use dev-master branch, else it will be in 2.0.0.

**Comment by kylekatarnls** [comment]
You can now upgrade to 2.0.0. Thanks.
