### ISSUE TITLE
Errors related to $

### ISSUE THREAD

**Issue by roxblnfk** [pug-php/pug#195]
Hello,

I encountered an issue with the following code (from official Phug documentation):
```pug
- $values = [1, 2, 3]
ul
  each $val in count($values) ? $values : ['There are no values']
    li= $val
```

I expected to get:
```html
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
</ul>
```

But I actually get:
```html
Invalid argument supplied for foreach()
```

I know that it will work with code:
```pug
each $val in count($values) ? values : ['There are no values']
```
(without **$**)

---

Following code:

```pug
- $t = 'hello'
div= true ? $t : 'nope'
```
presumably causes a PHP error: 

```
syntax error, unexpected '(', expecting variable (T_VARIABLE) or '{' or '$'
```

Thanks!

**Comment by kylekatarnls** [comment]
Maybe you miss this part about PHP-style vs. JS-style:
https://phug-lang.com/#use-javascript-expressions

Example to use PHP-style with Pug-php:
```php
<?php

use Pug\Pug;

include_once __DIR__ . '/vendor/autoload.php';

$pug = new Pug([
    'expressionLanguage' => 'php',
]);

$pug->display('p=$user->name', [
  'user' => (object) [
    'name' => 'Bob',        
  ],
]);
```

**Comment by roxblnfk** [comment]
I run this code in the [demo page](https://pug-demo.herokuapp.com/) and in the "PHP style" boxes of documentation pages.
Default is there `expressionLanguage='auto'`. *It is strange for the "PHP style" blocks*

If i check `expressionLanguage='php'` then it works. Sorry

**Comment by kylekatarnls** [comment]
`auto` mode is JS-style, it's there for backward-compatibility with Pug-php 2.x. I recommend to always set explicitly the mode to `js` or `php`. Glad it works now. :)
