### ISSUE TITLE
Error response in pug template

### ISSUE THREAD

**Issue by Freest10** [pug-php/pug#203]
Hello, I call the php method inside a pug template and I want that server to answer me 400 code with json in a pug template, how can I do this? header and the http_response_code php methods cause a template error.

Thanks!

**Comment by kylekatarnls** [comment]
Inside the template, you can do:
```pug
- header('Status: 404 Not Found');
| {
|   "foo": "bar"
| }
- exit
```
Outside the template, you should rather not to call render or display method and just call raw PHP:
```php
header('Status: 404 Not Found');
echo json_encode([
  'foo' => 'bar',
]);
exit;
```

**Comment by Freest10** [comment]
Thank you
