### ISSUE TITLE
Ternary conditional operator should be defined inside brackets

### ISSUE THREAD

**Issue by radiocity** [pug-php/pug#207]
Hello,

I encountered an issue with the following code:
```pug
a.footer-group-link(
  href = row.url,
  target = row.is_blank ? '_blank' : null,
  rel = row.nofollow ? 'nofollow' : null,
) !{row.title}
```

I expected to get a [link tag](https://codepen.io/radiocity/pen/LgqbPZ?editors=1000) with optional attributes

But I actually get:
```
ErrorException [ Parse Error ]: syntax error, unexpected ')'
/www/vendor/phug/renderer/src/Phug/Renderer/Adapter/EvalAdapter.php(12) : eval()'d code [ 2128 ]
```

[pug-php/pug](https://github.com/pug-php/pug) requires ternary conditional operator to be defined inside brackets, but [pugjs](https://github.com/pugjs/pug) ignores brackets at all. 
So, following code would work with both libraries:
```pug
a.footer-group-link(
  href = row.url,
  target = (row.is_blank ? '_blank' : null),
  rel = (row.nofollow ? 'nofollow' : null),
) !{row.title}
```

Thanks!

**Comment by kylekatarnls** [comment]
Fixed via phug/lexer 0.5.29, you can run `composer update` to get it working without brackets.
