### ISSUE TITLE
clear layout after render

### ISSUE THREAD

**Issue by zymanch** [pug-php/pug#215]
Hello,

I encountered an issue with the following code:
index.pug
```pug
extend layout
block content
  | test
```
layout.pug
```pug
html
  #title
  block content
```
debug_panel.pug
```pug
#debug_panel
```

```php
$outputHtml = $pug->renderFile('index.pug');
$debugHtml = $pug->renderFile('debug_panel.pug');
```
I expected to get for $debugHtml:
```html
<div id="debug_panel"></div>
```

But I actually get:
```html
<html><div id="title"></div></div>
```

Problem with Layout, it saved after first renderFile but i think it must be cleared.

Thanks!

**Comment by kylekatarnls** [comment]
Confirmed, we have a regression.

**Comment by kylekatarnls** [comment]
A temporary work-around can be:

```php
$outputHtml = $pug->renderFile('index.pug');
$pug->getRenderer()->initCompiler();
$debugHtml = $pug->renderFile('debug_panel.pug');
```

**Comment by kylekatarnls** [comment]
Please run `composer update` to upgrade phug/compiler and phug/renderer, it should fix it.
