### ISSUE TITLE
Multiple conditions not working with  `expressionLanguage => 'js'` option.

### ISSUE THREAD

**Issue by narirou** [pug-php/pug#216]
Hello,

I encountered an issue with the following code with rendering option `expressionLanguage => 'js'`:
```pug
doctype html
html
  body
    if falsy || !falsy || !falsy
      p 1
    else
      p 2
```

with data:
```json
array(
  'falsy' => false
)
``` 

I expected to get:
```html
<!DOCTYPE html>
<html>
  <body>
    <p>1</p>
  </body>
</html>

```

But I actually get:
```html
<!DOCTYPE html>
<html>
  <body>
    <p>2</p>
  </body>
</html>
```

[js-phpize-phug](https://github.com/pug-php/js-phpize-phug) 2.x will occer this error, but 1.x not occerred.

Thanks!

**Comment by kylekatarnls** [comment]
Hi, this a side effect of handling `myVariable || "default value"`

You can wrap:

```pug
doctype html
html
  body
    if falsy || (!falsy) || (!falsy)
      p 1
    else
      p 2
```

Or force js-phpize `booleanLogicalOperators` option:

```php
<?php

include __DIR__.'/vendor/autoload.php';

$pug = new Pug([
    'module_options' => [
        'jsphpize' => [
            'booleanLogicalOperators' => true,
        ],
    ],
]);
echo $pug->renderString('doctype html
html
  body
    if falsy || !falsy || !falsy
      p 1
    else
      p 2
', [
  'falsy' => false,
]);
```

It might be handled in a next major version of https://github.com/pug-php/js-phpize but not planned yet.

**Comment by kylekatarnls** [comment]
We're still open to pull-request if it can get both (the mixed type result and the correct precedence):

```js
shouldBeTrue = false || !false
shouldBe42 = false || 42
```

**Comment by narirou** [comment]
Thanks for quick answer.
Changing the condition requires modifying a lot of code so far, so we will try to change this options instead.

**Comment by kylekatarnls** [comment]
The difference you should check is everywhere you have `false || foo` you will now get `true` while you get previously `foo`, then `true && foo` will now give `!!foo` instead of  `foo`. Then you get the correct precedence between `&&` / `||` and other operators like `!`.

**Comment by matthewjumpsoffbuildings** [comment]
Is this issue documented anywhere? Because just ran into this, and thought we were going crazy, and now we are worried about this issue happening all over the place and we just didnt realise...

You just kinda expect multiple conditions to work as normal, and when it doesnt its super confusing, probably should be a big warning in the readme

**Comment by kylekatarnls** [comment]
You can propose your modification to the documentation here: https://github.com/phug-php/website
(or edit buttons in https://www.phug-lang.com/) but this certainly does not deserve a big blinking red warning.

**Comment by matthewjumpsoffbuildings** [comment]
Done 

https://github.com/phug-php/website/pull/6

**Comment by kylekatarnls** [comment]
Thanks. It's not that easy, but allowing the JS-like cast (`false || 42` giving `42`) + the correct operators precedence is still in the pipe for https://github.com/pug-php/js-phpize. And it's open to pull-requests if someone want to give a try.
