### ISSUE TITLE
syntax error, unexpected 'idx' (T_STRING), expecting ';'

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#222]
Hello,

I encountered an issue with the following code:
```pug
      - for (let idx = 0; idx < 5; idx++)
        div(
          class="BackLines-line"
          class= (excludedLines[idx] === false) ? "bg-t" : "bg-t05"
          class= (idx > 2) ? "d-n d-b@s" : "")
```

But I actually get:
<img width="885" alt="Screen Shot 2019-06-23 at 12 22 58 AM" src="https://user-images.githubusercontent.com/8479569/59968616-70dc0a80-954d-11e9-9a02-bbb13a5ed490.png">

Problem seems to be `let` with `var` it works fine.

Thanks!

**Comment by kylekatarnls** [comment]
Hi, I fixed it in the last version of [js-phpize](https://github.com/pug-php/js-phpize/releases/tag/2.4.1), please run `composer update` to get the bug fixed.
