### ISSUE TITLE
Undefined variable when using mixin with concatenation

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#229]
Problem is caused by `+ "/images/"` part.

<img width="677" alt="Screen Shot 2019-11-04 at 20 33 10" src="https://user-images.githubusercontent.com/8479569/68138903-af91c080-ff42-11e9-9332-f96e4d75e248.png">

<img width="781" alt="Screen Shot 2019-11-04 at 20 33 16" src="https://user-images.githubusercontent.com/8479569/68138912-b3bdde00-ff42-11e9-9d3c-e01c7c2f418f.png">

**Comment by kylekatarnls** [comment]
Hi,

> Problem is caused by `+ "/images/"` part.

I don't think so. According to the message, the local `assets_url` has not been provided. You should pass it to locals array (render parameter) or as a shared variable.

```php
$pug = new Pug(...);

$pug->displayFile('template.pug', [
  'assets_url' => '/directory',
]);
```

Thanks,

**Comment by sandrodz** [comment]
Well. I'm pretty sure I'm passing `assets_url`, because removing `+ "/images/"` it works.

**Comment by kylekatarnls** [comment]
`assets_url` will just return an empty string if not set with default settings. I can't reproduce this. Please provide a minimum chunk of code (including templates, the PHP code and locals values to be rendered) to copy-paste and reproduce your bug.

Ideally, if you can reproduce it on https://pug-demo.herokuapp.com/ you can just provide the template, settings and locals used.
