### ISSUE TITLE
Implement basedir option like the pugsjs one

### ISSUE THREAD

**Issue by leonpegg** [pug-php/pug#23]
basedir option is missing meaning all paths are relative and absoulte paths are not supported

**Comment by kylekatarnls** [comment]
Can you be more specific: do you mean the base directory of templates to be used with `include` and `extends`? If yes it's a good idea, it seems basedir is not available on pugjs either. But it could be easily added.

So we would have a basedir option in the compiler. If specified, all path would be concat to it, else all path would be relative to the current template.

I think allow both in the same time would lead to ambigus situations and bad practices.

Would it be what you have in mind?

**Comment by leonpegg** [comment]
Its exactly what i mean in jade/pug the option is avalible and can be passed as a compile value or local variable and when set allows both reletaive and absolute paths rule works like so

include header (this would be relative)
include ../header (this would be relative)
include /header (this would be absolute)

its extreamly helpful feature

**Comment by kylekatarnls** [comment]
Thanks, I never had to use that but I imagine it's very usefull if you have a package-like structure in your template folders.

I now found the basedir option in pugjs unit tests, too bad it's not documented here: http://jade-lang.com/api/

This is the reference I used to take.

So the specification will be as in pugjs and as you says:
`include header` **templatedir**/header.pug
`include ../header` **templatedir**/../header.pug
`include /header` **basedir**/header.pug

If basedir is not set and a path start with `/`: throw an exception.

Thanks for you help, planned for 2.0!

**Comment by leonpegg** [comment]
Hi I know I should really create a pull request etc but here is a quick mod to allow this (was desperate)
https://gist.github.com/leonpegg/8e98e0e8417511f17c771d5135d1a39b
it only enables basedir via compiler options but works well.

I will work on a full implementation and create a pull request over the next few days

**Comment by kylekatarnls** [comment]
Hi, thanks! I think it should be done in `getTemplatePath` and we should pass to it only the path end instead of the full path.

When done, the path calculation could be something like that:

``` php

    protected function getTemplatePath($path)
    {
        $isAbsolutePath = substr($path, 0, 1) === '/';
        if ($isAbsolutePath && !isset($this->options['basedir'])) {
            throw new \ErrorException("The 'basedir' option need to be set to use absolute path like $path", 29);
        }

        $path = ($isAbsolutePath
            ? rtrim($this->options['basedir'], '/\\')
            : dirname($this->filename)
        ) . DIRECTORY_SEPARATOR . $path;

        // The extension detection as it already is
        $extensions = $this->getExtensions();
        $extensions[] = '';
        foreach ($extensions as $extension) {
            if (file_exists($path . $extension)) {
                return realpath($path . $extension);
            }
        }

        throw new \InvalidArgumentException("The included file '$path' does not exists.", 22);
    }
```

I stop working on it for the moment waiting for your solution.

**Comment by leonpegg** [comment]
Hi as mentioned mine was a quick fix so my site would work :smile: 
I will work on the solution and submit merge request.

**Comment by kylekatarnls** [comment]
OK, no need to submit your merge request, while you did not start the implementation, I will continue what I started with `getTemplatePath`.

Thanks.

**Comment by kylekatarnls** [comment]
Thanks for all, the basedir option is now available on the master branch and should behave as in pugjs.

**Comment by kylekatarnls** [comment]
Now in the stable version 2.0.0. Thanks.
