### ISSUE TITLE
Compatibility problem with laracast

### ISSUE THREAD

**Issue by MindFlare56** [pug-php/pug#234]
Hello,

I encountered an issue with the following code:
```pug
include phpvars
    script(type='text/javascript').
      $(document).ready(function () {
        console.log('laracast Javascript::put example: ' + phpvars.age);
      })
```

I expected it to generate the html in order to make laracast work like in this exemple:
http://bonstutorial.com/laravel-transform-variable-from-controller-to-javascript/
```blade
@include('phpvars') 
<script type="text/javascript">   
    $(document).ready(function(){     
        console.log('laracast Javascript::put example: ' + phpvars.age);
    })
</script>
```

But I actually the include doesn't seem to do the same...
So I was wondering if there was an existing solution for this or else if it was possible to include
a blade file inside pug in order to fix this problem

Thanks!

**Comment by kylekatarnls** [comment]
Hello,

You script has no reason to be nested inside the include if it's only PHP vars as it sounds to be.

```php
include phpvars
script(type='text/javascript').
  $(document).ready(function () {
    console.log('laracast Javascript::put example: ' + phpvars.age);
  });
```

Then laravel-pug engine is the recommended way to use Pug inside Laravel:
https://github.com/BKWLD/laravel-pug

And finally I need you to precise "But I actually the include doesn't seem to do the same..." with the exact output you get in order to help further. And it may also depends on the content of phpvars, but I can't guess it as I don't know what it is.

Thanks.

**Comment by MindFlare56** [comment]
It was a copy paste error it is not nested into it

In fact it may be a laracast compatibility issue rather than pug
https://github.com/laracasts/PHP-Vars-To-Js-Transformer

when the file is included with blade laracast generate the following to be able to pass value from php to javascript. The phpvars file is empty but it is needed for the generation.
```html
<script>window.phpvars = window.phpvars || {};phpvars.foo = "bar";phpvars.age = 29;</script>
```

**Comment by kylekatarnls** [comment]
This sounds like an easy job for `View::share()` with no need for extra package:

```php
// In service or controller:
View::share('phpvars', [
  'age' => 22,
]);
```

```php
script(type='text/javascript').
  window.phpvars = !{json_encode(phpvars)};

  $(document).ready(function () {
    console.log('laracast Javascript::put example: ' + phpvars.age);
  });
```

Is there a particular reason to use this package?

**Comment by MindFlare56** [comment]
Oof...
That works perfectly!
Thanks a lot!
