### ISSUE TITLE
Apostrophe is escaped

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#238]
Hi,

```
div(class="bg-t3 c-p70 pv-m pv-l@m ph-s ph-l@m fz-24 fz-36@m lh-xxs g-b fb1/1 fb1/2@m")= quote
```

string content:

```
Metreveli's
```

is rendered:

<img width="813" alt="Screen Shot 2020-06-08 at 14 31 44" src="https://user-images.githubusercontent.com/8479569/84020981-d1e63380-a994-11ea-8c04-78f2067dbeed.png">

obviously adding !=quote fixes this. But why are `'` and other enttities escaped?

**Comment by kylekatarnls** [comment]
Hello, I'm pretty sure `quote` does not content `Metreveli's` but an already escaped string. And that would be the cause: it's escaped twice.

As you may see, if `quote` actually contains what you say, it works fine:
```pug
- quote = "Metreveli's"
div(class="bg-t3 c-p70 pv-m pv-l@m ph-s ph-l@m fz-24 fz-36@m lh-xxs g-b fb1/1 fb1/2@m")= quote
```

**Comment by sandrodz** [comment]
You are absolutely right. Sorry.
