### ISSUE TITLE
Option to disable html minficiation

### ISSUE THREAD

**Issue by sandrodz** [pug-php/pug#239]
Hi

I could not find option to disable html minification.
Played with pretty but it did not do anything.

<img width="926" alt="Screen Shot 2020-06-15 at 13 49 10" src="https://user-images.githubusercontent.com/8479569/84643511-0155ec80-af0f-11ea-99bd-a4fcdf4859c7.png">

**Comment by kylekatarnls** [comment]
I ran this very basic code:
```php
<?php

use Pug\Pug;

include 'vendor/autoload.php';

(new Pug(['pretty' => true]))->display('div: p: Hello');

echo "\n";

(new Pug(['pretty' => false]))->display('div: p: Hello');
```

And I get:
```html
<div>
  <p><b>Hello</b></p>
</div>

<div><p><b>Hello</b></p></div>
```

Please provide:
- [ ] Code I can copy-paste (not screenshot)
- [ ] With static data and only code involving Pug/Phug (for instance, I can't debug your `$this->dev_env` value while if it's false, your change are simply not taken into account and I don't see neither what happen to `$this->options` before it's passed to the renderer, and I can't even check how and if it's really passed to it)
- [ ] The actual output you get (still provide some static template string I can inspect)
- [ ] The output you expect

If you follow the issue pattern we provide, it will helps us to help you.
