### ISSUE TITLE
Array values not converted to objects during interpolation in attributes

### ISSUE THREAD

**Issue by weotch** [pug-php/pug#30]
With this data:

``` php
[ 
  'feature' => [
    'image' => '/img/path.jpg'
  ]
]
```

This pug...

``` pug
.featured(style='background-image: url(/img/#{feature.image});')
```

... fails with an `Array to string conversion` exception.  But this works:

``` pug
.featured(style='background-image: url(/img/#{feature["image"]});')
```

I should be able to use `feature.image`, right?
## 

Thanks for the package!  Incidentally, I set up this Laravel adapter https://github.com/BKWLD/laravel-pug

**Comment by kylekatarnls** [comment]
Here it seems the dot is interpreted as a concatenation, but indeed, we try to implement the dot as the JS dot, and as it already work here:

``` pug
//- Get image property/entry in feature
p=feature.image

//- Concat feature and image
p=feature . image
```

So it should be available in interpolation `#{}` also as you mention.

This issue should be solved as a patch of the 2.0 (for 2.0.X)

Many thanks!

**Comment by weotch** [comment]
Awesome!  Btw, LOVE that you implemented the dot syntax for objects.  👍

**Comment by kylekatarnls** [comment]
2.0.0 is out with the fix, I close this issue.
