### ISSUE TITLE
Error while setting dynamic HTML attributes

### ISSUE THREAD

**Issue by JumpIfBelow** [pug-php/pug#32]
While I'm trying to achieve a dynamic A tag with its href attribute, I'm facing an error with PHP. Actually, Pug does not parse the content correctly in this example of code:

`a(href="?id=#{myObj.id}")`

This will throw an error like trying to convert an object to string. Actually, it is trying to achieve the PHP's concatenation (the result looks like "`<?php echo $myObj . $id ?>`"), that's why there is the bug.

The workaround for me was to do something like this:

`a(href="?id=#{myObj->id}")`

which is not a Pug syntax, but it actually works.

EDIT:
To be more complete, still the same issue if writting the code with the equivalent:
`a(href="?id=" + myObj.id)`

**Comment by kylekatarnls** [comment]
Thanks for your report, I close this issue since it's related to #30 you can add your comments on this issue.
