### ISSUE TITLE
Blanks between HTML tags

### ISSUE THREAD

**Issue by JumpIfBelow** [pug-php/pug#34]
Just a simple problem, but this leads me to a real issue.

When I want to display a textarea, the code is really simple:

`textarea(name="comments")`
But actually, the output code is
`<textarea name="comments"><!-- some spaces here --></textarea>`

And that's the problem: I don't want any blanks in my textarea as there is nothing inside, it will appear weird to the user when filling the form.
It appears no matter I set the pretty print to true or false. Cache (or not) does not change a thing too.

Is there a way like Twig, for example, to remove those blanks. (e.g. in Twig: `{{- myVar -}}` will remove the blanks between the Twig tag and the HTML tag, in both left and right side)

**Comment by kylekatarnls** [comment]
Ineed, it's a regression. It will be fixed ASAP.

Thanks for report.

**Comment by kylekatarnls** [comment]
If you use the dev-master, you can update and it should be fixed for you. Else it will be fixed in 2.0.0.

Many thanks!

**Comment by kylekatarnls** [comment]
Fixed. If you still have some trouble after upgrading to 2.0.0, feel free to re-open.
