### ISSUE TITLE
Issue with parenthesis in attributes

### ISSUE THREAD

**Issue by weotch** [pug-php/pug#35]
This pug:

``` jade
.featured(class=(true==true)?'on':'off')
```

Produces a `syntax error, unexpected ')', expecting variable (T_VARIABLE) or '$'` exception.  It is fixed by:

``` jade
.featured(class=true==true?'on':'off')
```

I ran into this while porting a jade-js project to PHP

**Comment by kylekatarnls** [comment]
Thanks for the report. I just pushed a commit that should fix it.

**Comment by kylekatarnls** [comment]
Fixed. It still have some trouble after upgrading to 2.0.0, feel free to re-open.
