### ISSUE TITLE
underscore prefixed names not recognized

### ISSUE THREAD

**Issue by hax** [pug-php/pug#48]
``` pug
each _x in [1,2,3]
  - var_dump(_x)
```

Got Parse error: syntax error, unexpected ')', expecting '('

**Comment by kylekatarnls** [comment]
Hi, indeed, the _x should be translated to $_x and it's not. We'll fix it.

Meanwhile, you can use:

``` pug
each x in [1,2,3]
  - var_dump(x)
```

**Comment by kylekatarnls** [comment]
It's fixed on master, it will be released on 2.2

**Comment by kylekatarnls** [comment]
2.2 released, please update.

**Comment by glodov** [comment]
It appears in version ^2.6.

I want to use __page, when I use page it does work.
I tried $__page, does not help.

```pug
head
  title= __page.seo.title
  meta(charset='utf-8')
```
