### ISSUE TITLE
Allow extra semicolon in output

### ISSUE THREAD

**Issue by hax** [pug-php/pug#49]
``` pug
= test;
!= test;
```

Currently extra `;` will cause parser error. Though it's redundant, old jade-php allow this and there are many in the repo of my team. So for compatibility could you allow this?

**Comment by kylekatarnls** [comment]
Our purpose is to get the closest to the pug-js version, and as you can see on the demo (http://jade-lang.com/) the `;` is not allowed.

I will see if it could be done easily. But I encourage you to use the proper syntax without `;`.

You can also patch it this way:

``` php
$pug = new \Pug\Pug(array(
    'postRender' => function ($phpCode) {
        return str_replace(';)', ');', $phpCode);
    },
));
```

**Comment by kylekatarnls** [comment]
I was able to allow trailing `;` with no regression. So it's commited and it will be available on next release.

Thanks.

**Comment by kylekatarnls** [comment]
2.2 released, please update.
