### ISSUE TITLE
Need more info for parsing error report

### ISSUE THREAD

**Issue by hax** [pug-php/pug#50]
I just got many errors like:

```
( ! ) Fatal error: Uncaught exception 'ErrorException' with message 'Unexpected value: link']}'' in .../htdocs/vendor/pug-php/pug/src/Jade/Compiler.php on line 285
```

Such error report is not very helpful. I guess it come from some syntax error in my pug source, but current error report give no clue.

**Comment by kylekatarnls** [comment]
With a `try-catch`, you can get the trace:

``` php
$pug = new \Pug\Pug();
try {
  $pug->render('your-template');
} catch (\Exception $e) {
  echo '<pre>' . $e->getTraceAsString() . '</pre>';
}
```

And you should see what method of Compiler is called and where in the generated PHP code.

It should be just before `link']}` in your template code. If you see some blocks with this string, you can copy them here for analyse.

**Comment by kylekatarnls** [comment]
We could pass to Compiler methods some parsing infos (template file, template line of the original parsed code) when some "debug" option would be true.

**Comment by kylekatarnls** [comment]
I found a way to inject more informations (pug node type, tag name when it's a tag, file line and file name when it's rendered from a pug file) on the fly in the exceptions thrown. It weel be implemented in the next release with no need to set any option since thoses errors occurs during compilation and not during rendering.

**Comment by kylekatarnls** [comment]
With the new version 2.2.1, you should have information about, the tag, file and line where errors happen.

**Comment by kylekatarnls** [comment]
**pug-php 3** comes with the new error handling system of https://github.com/phug-php/phug and now provides the line and offset from the Pug source file.
