### ISSUE TITLE
include, extends

### ISSUE THREAD

**Issue by jorjsmile** [pug-php/pug#63]
in my index.pug
I have 

> include front/header.pug

Compiler always tell's : "Page not found."
Looking at source of  vendor/pug-php/pug/src/Jade/Jade.php:compile:217 method -  I see:

>   $parser = new Parser($input, null, $this->options);

Mb, it should be 

>  $parser = new Parser($input, $FILENAME, $this->options);

So the parser could detected local directory name? And after load dependency?

**Comment by jorjsmile** [comment]
Ok, got it. If  I will send to compile not source, but a file - it will render properly. But I think you should extend method compile, so it take 2nd parameter, of filename.

**Comment by kylekatarnls** [comment]
Hi,

The right way to do it is to specify the basedir option to your templates folder and specify absolutes pathes.

Else if you work with include and extends it would be a bad idea to render raw sources instead of files pathes.
