### ISSUE TITLE
Inline filters

### ISSUE THREAD

**Issue by s4msung** [pug-php/pug#68]
It seems only Block-Style filters are supported:

``` pug
h1
  :i18n
    msg_id
```

Inline-Style filters

```
h1
  | ...
  :i18n msg_id
  | ...
```

``` pug
h1 ... #[:i18n msg_id] ...
```

are currently throwing ErrorException with "Expected indent, but got text in 1th line: ..."

pug-php version 2.4.1

**Comment by kylekatarnls** [comment]
Confirmed,

This can be fixed in the future.

Note than filters may not be th best fit for those kind of multiple quick function calls. For example, pug-php is gettext-capable ans this is a reference for i18n:

``` pug
h1
  | ...
  =_('msg_id')
  | ...

h2=_('msg_id')
```

**Comment by s4msung** [comment]
Awesome! Didn't knew the gettext-capability

**Comment by kylekatarnls** [comment]
Hi, inline filter are now available.
