### ISSUE TITLE
Don't require a leading slash to use the `basedir` option when extending

### ISSUE THREAD

**Issue by thelucre** [pug-php/pug#69]
The Jade extends syntax doesn't require a leading slash. 
https://pugjs.org/language/extends.html

Currently, for our Laravel parser, the leading slash is required for the `basedir` option to be used when searching for the template path.
https://github.com/BKWLD/laravel-pug#extending-layouts 

Is it possible to use the `basedir` option regardless of the leading slash, in order to stay closer to the Jade/Pug syntax? 
https://github.com/pug-php/pug/blob/master/src/Jade/Parser.php#L66

**Comment by kylekatarnls** [comment]
Hi,

As in pug-js, a path starting with a slash is interpreted as an absolute path (from basedir root) and other paths are interpreted as relatives ones.

https://github.com/pugjs/pug-load/blob/c9165d13c2e1d4b7010925b7e0bbfe37bda5b8aa/index.js#L64

``` js
filename = path.join(filename[0] === '/' ? options.basedir : path.dirname(source.trim()), filename);
```

Please let me know if I understood something wrong.
