### ISSUE TITLE
Object properties cannot concatenate with strings

### ISSUE THREAD

**Issue by StephanAtG2** [pug-php/pug#71]
Consider 
`input(type="checkbox", name="group["+group.id+ "]")`

Compiles to
`<input type="checkbox" name="group[{...}].id]">`
instead of
`<input type="checkbox" name="group[the_id]">`

but works when not concatenating

**Comment by kylekatarnls** [comment]
Hi,

We cannot handle in the same time `.` as PHP concantenation and `.` as JS property getter. So with the option **expressionLanguage** set to `"auto"`, we guess what it could be depending on the context.

But I can fix it for **expressionLanguage** js.

I'll give you news soon.

**Comment by kylekatarnls** [comment]
Thanks, added to Pug.

Now for an object depending on the expressionLanguage used you can:

expressionLanguage = php

``` pug
input(type="checkbox" name="group[" . $group->id . "]")
```

expressionLanguage = js

``` pug
input(type="checkbox" name="group[" + group.id + "]")
```

expressionLanguage = auto

``` pug
input(type="checkbox" name="group[" + group->id + "]")
```

For an array:

expressionLanguage = php

``` pug
input(type="checkbox" name="group[" . $group['id'] . "]")
```

expressionLanguage = js

``` pug
input(type="checkbox" name="group[" + group.id + "]")
```

expressionLanguage = auto

``` pug
input(type="checkbox" name="group[" + group['id'] + "]")
```
