### ISSUE TITLE
Names for Functions

### ISSUE THREAD

**Issue by dreerr** [pug-php/pug#73]
I make heavy use of ProcessWires translation function called by `__('String to translate')` sadly this does not work with pug/jade, any other function named `doSomething()` works as expected. Anywhere I can change this?

**Comment by kylekatarnls** [comment]
I use the GetText `_()` function and that works well, I will study if double-underscore can cause conflict.

**Comment by dreerr** [comment]
Thank you very much Kyle 🤗
