### ISSUE TITLE
Current examples and project not working

### ISSUE THREAD

**Issue by debo** [pug-php/pug#78]
I am trying to adopt this library for one of my pet projects but I don't seem to be able to achieve any working result. As last resource I did try to run the provided examples using the PHP built-in web server but also in that case I didn't seem to be able to make it work.

Out of the box after starting the built-in web server within the example folder produces an `E_NOTICE` that `PATH_INFO` is not set, that's easy to temporarily work around suppressing notice errors, however, even with notice suppressed I can't get anything but a blank page.

It has to be noted that pug defaults to `.pug` as extension but all the file presents in the folder are `.jade` so I decided to force the latter upon creation of the pug object but again without success, I always get a blank page. 

The disconcerting thing is that there are no visible errors reported. 

Any ideas?

**Comment by debo** [comment]
Ok it looks likes I found the cause for the non working examples and submitted the fix in PR https://github.com/pug-php/pug/pull/79

**Comment by kylekatarnls** [comment]
Oh, thanks, indeed it was obsolete. I will try to improve examples someday with some other technologies. Your work is really much appreciated.

**Comment by debo** [comment]
No problem, my pleasure.

**Comment by debo** [comment]
Now I will try to see if I can make it work in the pet project, I am still failing with that 😞

**Comment by kylekatarnls** [comment]
Thanks for your feedback, please give me the specificities of your project, the code that load Pug and the directories and files pathes.

**Comment by debo** [comment]
@kylekatarnls I eventually managed to get it work but the "issue" if we can call it such is that when you instantiate the pug renderer and you define a `basedir`, such `basedir` doesn't seem to be then prepended to the file name specified to be included, in other words to include a file I don't seem to be able to use path relative to `basedir`. Moreover, but this is more like a feature request, there is no support for multiple include paths.

I hope that clarifies a bit more.

**Comment by kylekatarnls** [comment]
We followed the Pug-js spec that is:
- if the path start with /, we use basedir and append the included/extended path after it;
- else we consider the path relative to the current pug file.

Maybe these examples can help:
https://github.com/pug-php/pug/issues/23#issuecomment-232298477

**Comment by debo** [comment]
@kylekatarnls I am not referring to that but to the php part. Basically if I have:

``` php
$pug = new Pug(array(
    'cache' => 'var/cache/pug',
    'basedir' => 'path/to/pug/templates/',
    'upToDateCheck' => false,
);
$pug->render('my-page.pug');
```

it doesn't worh but everything is fine if I do

``` php
$pug = new Pug(array(
    'cache' => 'var/cache/pug',
    'basedir' => 'path/to/pug/templates',
    'upToDateCheck' => false,
);
$pug->render('path/to/pug/templates/my-page.pug');
```

**Comment by kylekatarnls** [comment]
Indeed, basedir is not used this way, it's a template option for include and extend as it is in the original repository: https://github.com/pugjs/pug/search?utf8=%E2%9C%93&q=basedir

I recommand this approach:

``` php
// Get the templates directory relatively to the view renderer.
$templatesDirectory = __DIR__ . '/views';
$pug = new Pug(array(
    'cache' => 'var/cache/pug',
    // Pass it to basedir
    'basedir' => $templatesDirectory,
    'upToDateCheck' => false,
));
// Prefix render calls with it.
$pug->render($templatesDirectory . '/my-page.pug');
```

Note that you can also get it from pug:

``` php
$pug = new Pug(array(
    'basedir' => __DIR__ . '/views',
));
$pug->render($pug->getOption('basedir') . '/my-page.pug');
```

**Comment by debo** [comment]
@kylekatarnls so to make it clear to me, that's only to be able to import file from a relative path to `basedir` but render always need a absolute one?

**Comment by kylekatarnls** [comment]
Like any PHP function (such as `file_get_contents`), the relative pathes are relative to `cwd` (current working directory), so this is the relative way to do it:

``` php
chdir(__DIR__ . '/views');
$pug = new Pug(array(
    'basedir' => '.',
));
$pug->render('my-page.pug');
```

**Comment by debo** [comment]
Yeah I know that, what I meant is that `basedir` option affect only files included via `import` in a jade/pug template. Otherwise it's ignored if `render` is invoked.

**Comment by kylekatarnls** [comment]
Yes, and in my humble opinion it should stay that way as if we do the same with pugjs:

``` js
var pug = require('pug');

var html = pug.renderFile('test.pug', {
    basedir: __dirname + '/views'
});

console.log(html);
```

The path called is `__dirname + '/test.pug'` and not `__dirname + '/views/test.pug'`

**Comment by debo** [comment]
Got it, got it. It's fine I simply wanted to make sure I was on the same page, I don't mind which way it is once I know how it is intended to work. Thanks for the clarification.
