### ISSUE TITLE
Single method to assign variable?

### ISSUE THREAD

**Issue by dzpt** [pug-php/pug#83]
I see only render is the method can assign variable to the template.
Is there any way or method to assign variable separately like:
`$pug->assign('abc',$abc);`

**Comment by kylekatarnls** [comment]
Yes, this method is `share`:

``` php
$pug->share('abc', $abc);
```

Then all the next render will have this shared variable and the variables passed in the render method.

You can also use share with an array:

``` php
$pug->share(array(
  'abc' => $abc,
  'answer' => 42,
));
```
