### ISSUE TITLE
Can´t pass variables to &attributes(attributes) in a mixin

### ISSUE THREAD

**Issue by usingthesystem** [pug-php/pug#88]
I want to pass variables to the mixin within the attributes param.
This doesn´t work as expected because it is not inserting the variables just the variable name as a string. I tried also with `$` but it also didn´t help.

Do you think you can fix this?

`Mixin `
```pug
mixin module()
  div.module()&attributes(attributes)
    block
```

`Variables` passed to the `Template`
```php
<?php
array(
  'moduleTitle' => 'I am a module',
  'customClassKey' => 'custom-class-value',
  'customAttributeKey' => 'custom-attribute-value'
)
```

`Template`
```pug
!!! 5
html(lang="en")
  body
    +module()(class=customClassKey data-customDataAttribute=customAttributeKey)
      h1= moduleTitle
```

`HTML Result `
Output which doesn´t have the attribute variable just the keys of the passed variables
```html
<!DOCTYPE html>
<html lang="en">
  <body>
  <div data-customAttribute="customAttributeKey" class="customClassKey module">
    <h1>I am a module</h1>
  </div>
  </body>
</html>
```

**Comment by kylekatarnls** [comment]
Hi, I confirm this bug, there is no work-around for dynamic values in attributes via the mixin.

**Comment by usingthesystem** [comment]
@kylekatarnls thx for the quick reply. 
Do you have already a idea how much work this will be? 
Do you plan anytime soon to fix this bug?
If you like i maybe could assist you

**Comment by kylekatarnls** [comment]
Hi,

I did not find what's wrong. I'll go deeper if I can. But I cannot fix it soon because I'm very busy with the js-phpize Pug sub-project and I started a new project of refactoring Pug from scratch. I would not say too much about it. I hope this could solve a lot of problems of the current version but it could take some time.

So feel free to propose a pull-request if you have time.

**Comment by kylekatarnls** [comment]
Hi, there is a new option now available to use the native pugjs engine (as an alternative if you still have blocking bugs with the PHP engine):

```php
$pug = new Pug(array(
    'pugjs' => true
));
echo $pug->render('
!!! 5
html(lang="en")
  body
    +module()(class=customClassKey data-customDataAttribute=customAttributeKey)
      h1= moduleTitle
');
```
This is a pure wrapper solution with no PHP support in templates (all run with node.js).

**Comment by webdevian** [comment]
@kylekatarnls Will using this option disable caching?

**Comment by kylekatarnls** [comment]
Yes, since pugjs cache the template inside the process memory and since the pug-cli is called isolated (via `shell_exec`) , we do not benefit of the cache. If you see a way to get cache working, I'm very interested. Currently I'm stuck.

**Comment by webdevian** [comment]
I can't think of a way to do it across node and php unless the caching is done in node and persisted to disk

**Comment by kylekatarnls** [comment]
I see now two ways:

**The faster way on runtime:**
Run a node.js server that will serve a web-service, PHP access this web-server via cURL (HTTP) sending file path/content and variables as JSON POST data to a URL like http://localhost:1234/pug-web-service, the web-service returns the compiled HTML (cache the pre-compiled template), then it's faster when you re-call with the same template.

**The easiest way but slower:**
Use the pug-cli `--client` option that return a pre-compiled JS function, so we can cache templates as JS files, then temporary save variables on the fly in JSON file, then call JS script to render such as:
```js
var template = require('./cache/' + some_secure(process.argv[2]) + '.js');
var variables = require('./tmp/' + some_secure(process.argv[3]) + '.json');

console.log(template(variables));
```

I will try some experiences.

**Comment by kylekatarnls** [comment]
Second method implemented.

**Comment by kylekatarnls** [comment]
You can update to `3.0.0-alpha2` (witouht `pugsjs` option), it should be fixed. Please don't hesitate to test the new pug-php 3 and give us your feedback.
