### ISSUE TITLE
Can't pass function result to mixin directly

### ISSUE THREAD

**Issue by J5lx** [pug-php/pug#92]
This code:

```pug
.form__element
  +site-select(trans('auth.signin.site'))
```

results in `trans('auth.signin.site' Missing closing: )`.

However this code works just fine:

```pug
.form__element
  - $placeholder = trans('auth.signin.site')
  +site-select($placeholder)
```

Same code in JS syntax works as well:

```pug
.form__element
  - placeholder = trans('auth.signin.site')
  +site-select(placeholder)
```

MWE for site-select:

```pug
mixin site-select(placeholder)
  = placeholder
```

Possibly related: #84

**Comment by kylekatarnls** [comment]
Thanks, I think it could be fixed in the mixin call RegExp.

**Comment by kylekatarnls** [comment]
Hi, I have still some adjustements to do to perfectly handle parentheses in mixin calls but you can yet `composer update` to get Pug 2.4.9 to calls like `+site-select(trans('auth.signin.site'))` in your templates.

**Comment by kylekatarnls** [comment]
Now, mixin calls should handle any valid PHP syntax in it. Just upgrade to the version 2.5.0

**Comment by j5lx** [comment]
I finally got to try this out, and I can confirm that it works. Thanks! I'll have a look at the magic method thing next.
